name: Moonshot Pipeline CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Cache pip packages (optional but faster)
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5️⃣ Run the Moonshot CSV pipeline
      - name: Run pipeline
        run: python moonshot_pipeline_interactive.py

      # 6️⃣ Upload filtered CSV as artifact
      - name: Upload filtered CSV
        uses: actions/upload-artifact@v4
        with:
          name: filtered-data
          path: data/filtered_data.csv
          retention-days: 7

      # 7️⃣ Upload Plotly visualizations (HTML)
      - name: Upload visualizations
        uses: actions/upload-artifact@v4
        with:
          name: visualizations
          path: data/visualizations/
          retention-days: 7

          - name: Run training script
  run: python train_model.py

- name: Upload model artifact
  uses: actions/upload-artifact@v4
  with:
    name: random-forest-model
    path: models/random_forest.pkl

