data:
  raw_path: "data/incoming/"
  curated_path: "data/curated/"

ingestion:
  sources: ["csv"]   # options: csv, api, huggingface, kaggle
  continuous: true
  poll_interval: 5   # seconds

storage:
  format: "parquet"
  compression: "snappy"

schema:
  enable_auto: true
  save_path: "data/schema/"
  versioning: true

drift:
  enable: true
  history_limit: 5   # keep last 5 schema versions
