name: Moonshot Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn joblib matplotlib pyyaml pytest

      - name: Run filter.py
        run: python filter.py

      - name: Run train_model.py
        run: python train_model.py

      - name: Run tests
        run: pytest -v --maxfail=1 --disable-warnings
