name: Moonshot Pipeline CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Moonshot pipeline
        run: python moonshot_pipeline_interactive.py

      - name: Upload filtered CSV
        uses: actions/upload-artifact@v4
        with:
          name: filtered-data
          path: data/filtered_data.csv
          retention-days: 7

      - name: Upload visualizations
        uses: actions/upload-artifact@v4
        with:
          name: visualizations
          path: data/visualizations/
          retention-days: 7

