name: Moonshot Data Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Data Filter & Model Training
      run: |
        python filter.py

    - name: Upload filtered dataset
      uses: actions/upload-artifact@v4
      with:
        name: filtered-data
        path: data/curated/filtered_data.csv

    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: random_forest.pkl
        
    - name: Run script filter
      run: python filter.py

    - name: Run training script 
      run: python train_model.py

    - name: Run tests
      run: pytest -v 

    - name: Run debug
      run: python debug.py
