name: Run Data Filter Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-filter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run filter script
        run: |
          python filter.py

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v4
        with:
          name: random-forest-model
          path: random_forest.pkl
